### ISSUE TITLE
HM-Dis-EP-WM55 lines are cleared

### ISSUE THREAD

**Issue by ecdlguy** [rdmtc/node-red-contrib-ccu#120] opened 2020-06-14 19:32 UTC
When trying to alter a single line of the the HM-Dis-EP-WM55 (eInk Display) using the display node input, the other lines are cleared. This forces the user to "cache" the other lines as context data and always send all lines to the display although only on line has changed, leading to an increased duty cycle.

cheers, Thorsten

**Comment by JoeHaenf** [comment] 2020-11-05 21:05
Looking at the code of the ccu-display.js node, i suspect the problem is that every output line is filled with a space, even when it is not provided in the input 
see 
```
function convertString(string) 
...
if (!string) {
  string = ' ';
}
```
I think a null reference should result in skipping the line completely, while providing a blank could then be used to intentionally clear the line.

I am sorry, I am new to all this so I am not able to test this myself and provide a pull request (yet).

**Comment by konne** [comment] 2020-11-19 17:41
@ecdlguy and @JoeHaenf 
This is not so easy, so I introduced a disable flag for each line, to make it possible in the config to disable lines that should not be written. If you know to write in the msg only you change, this is transferred to the display.
You could check out my PR and check.

IMPORTANT: if you like to change the symbol/color/text in a line, you have to change everything in that line.
This is only possible per line.

**Comment by JoeHaenf** [comment] 2020-11-24 19:45
@konne 
Thanks for your work. I tested it locally and it works fine for me in every constellation.
You might still update the helpfiles under locales to reflect the new `disableX` option.

**Comment by konne** [comment] 2020-11-26 07:44
@JoeHaenf danke für das Testen und den Hinweis. Habe die Doku noch angepasst.

@hobbyquaker kannst du bitte ein Feedback geben, oder schreiben wie bei dir im Repo
der Contribution Prozess gedacht ist, Danke

**Comment by hobbyquaker** [comment] 2021-03-06 15:59
@konne einfach PR stellen, hab da keine besonderen Anforderungen. Wünschenswert wäre es es vorher einmal zu linten und zu testen: `npm install`, `npm run lintonly`, `npm run testonly`. Die meisten linting issues lassen sich automatisch mit `npm run lintfix` lösen. Und vielen Dank für den PR noch! :+1:

**Closed by hobbyquaker** 2021-03-06 15:59 UTC
Labels: 🐛bug, 🤔to be clarified
